# A CI/CD pipeline that automates the deployment of docker image of node.js file to kubernetes cluster
name: node.js CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

